var search={
  "Calibration of light direction vector 1.JPG": "http://i3mainz.de/metadata/1.JPG_ld_calibration",
  "Calibration of light direction vector 10.JPG": "http://i3mainz.de/metadata/10.JPG_ld_calibration",
  "Calibration of light direction vector 11.JPG": "http://i3mainz.de/metadata/11.JPG_ld_calibration",
  "Calibration of light direction vector 12.JPG": "http://i3mainz.de/metadata/12.JPG_ld_calibration",
  "Calibration of light direction vector 13.JPG": "http://i3mainz.de/metadata/13.JPG_ld_calibration",
  "Calibration of light direction vector 14.JPG": "http://i3mainz.de/metadata/14.JPG_ld_calibration",
  "Calibration of light direction vector 15.JPG": "http://i3mainz.de/metadata/15.JPG_ld_calibration",
  "Calibration of light direction vector 16.JPG": "http://i3mainz.de/metadata/16.JPG_ld_calibration",
  "Calibration of light direction vector 17.JPG": "http://i3mainz.de/metadata/17.JPG_ld_calibration",
  "Calibration of light direction vector 18.JPG": "http://i3mainz.de/metadata/18.JPG_ld_calibration",
  "Calibration of light direction vector 19.JPG": "http://i3mainz.de/metadata/19.JPG_ld_calibration",
  "Calibration of light direction vector 2.JPG": "http://i3mainz.de/metadata/2.JPG_ld_calibration",
  "Calibration of light direction vector 20.JPG": "http://i3mainz.de/metadata/20.JPG_ld_calibration",
  "Calibration of light direction vector 21.JPG": "http://i3mainz.de/metadata/21.JPG_ld_calibration",
  "Calibration of light direction vector 22.JPG": "http://i3mainz.de/metadata/22.JPG_ld_calibration",
  "Calibration of light direction vector 23.JPG": "http://i3mainz.de/metadata/23.JPG_ld_calibration",
  "Calibration of light direction vector 24.JPG": "http://i3mainz.de/metadata/24.JPG_ld_calibration",
  "Calibration of light direction vector 25.JPG": "http://i3mainz.de/metadata/25.JPG_ld_calibration",
  "Calibration of light direction vector 26.JPG": "http://i3mainz.de/metadata/26.JPG_ld_calibration",
  "Calibration of light direction vector 27.JPG": "http://i3mainz.de/metadata/27.JPG_ld_calibration",
  "Calibration of light direction vector 28.JPG": "http://i3mainz.de/metadata/28.JPG_ld_calibration",
  "Calibration of light direction vector 29.JPG": "http://i3mainz.de/metadata/29.JPG_ld_calibration",
  "Calibration of light direction vector 3.JPG": "http://i3mainz.de/metadata/3.JPG_ld_calibration",
  "Calibration of light direction vector 30.JPG": "http://i3mainz.de/metadata/30.JPG_ld_calibration",
  "Calibration of light direction vector 31.JPG": "http://i3mainz.de/metadata/31.JPG_ld_calibration",
  "Calibration of light direction vector 32.JPG": "http://i3mainz.de/metadata/32.JPG_ld_calibration",
  "Calibration of light direction vector 33.JPG": "http://i3mainz.de/metadata/33.JPG_ld_calibration",
  "Calibration of light direction vector 34.JPG": "http://i3mainz.de/metadata/34.JPG_ld_calibration",
  "Calibration of light direction vector 35.JPG": "http://i3mainz.de/metadata/35.JPG_ld_calibration",
  "Calibration of light direction vector 36.JPG": "http://i3mainz.de/metadata/36.JPG_ld_calibration",
  "Calibration of light direction vector 37.JPG": "http://i3mainz.de/metadata/37.JPG_ld_calibration",
  "Calibration of light direction vector 38.JPG": "http://i3mainz.de/metadata/38.JPG_ld_calibration",
  "Calibration of light direction vector 39.JPG": "http://i3mainz.de/metadata/39.JPG_ld_calibration",
  "Calibration of light direction vector 4.JPG": "http://i3mainz.de/metadata/4.JPG_ld_calibration",
  "Calibration of light direction vector 40.JPG": "http://i3mainz.de/metadata/40.JPG_ld_calibration",
  "Calibration of light direction vector 41.JPG": "http://i3mainz.de/metadata/41.JPG_ld_calibration",
  "Calibration of light direction vector 42.JPG": "http://i3mainz.de/metadata/42.JPG_ld_calibration",
  "Calibration of light direction vector 43.JPG": "http://i3mainz.de/metadata/43.JPG_ld_calibration",
  "Calibration of light direction vector 44.JPG": "http://i3mainz.de/metadata/44.JPG_ld_calibration",
  "Calibration of light direction vector 45.JPG": "http://i3mainz.de/metadata/45.JPG_ld_calibration",
  "Calibration of light direction vector 46.JPG": "http://i3mainz.de/metadata/46.JPG_ld_calibration",
  "Calibration of light direction vector 47.JPG": "http://i3mainz.de/metadata/47.JPG_ld_calibration",
  "Calibration of light direction vector 48.JPG": "http://i3mainz.de/metadata/48.JPG_ld_calibration",
  "Calibration of light direction vector 49.JPG": "http://i3mainz.de/metadata/49.JPG_ld_calibration",
  "Calibration of light direction vector 5.JPG": "http://i3mainz.de/metadata/5.JPG_ld_calibration",
  "Calibration of light direction vector 50.JPG": "http://i3mainz.de/metadata/50.JPG_ld_calibration",
  "Calibration of light direction vector 51.JPG": "http://i3mainz.de/metadata/51.JPG_ld_calibration",
  "Calibration of light direction vector 52.JPG": "http://i3mainz.de/metadata/52.JPG_ld_calibration",
  "Calibration of light direction vector 53.JPG": "http://i3mainz.de/metadata/53.JPG_ld_calibration",
  "Calibration of light direction vector 54.JPG": "http://i3mainz.de/metadata/54.JPG_ld_calibration",
  "Calibration of light direction vector 55.JPG": "http://i3mainz.de/metadata/55.JPG_ld_calibration",
  "Calibration of light direction vector 56.JPG": "http://i3mainz.de/metadata/56.JPG_ld_calibration",
  "Calibration of light direction vector 57.JPG": "http://i3mainz.de/metadata/57.JPG_ld_calibration",
  "Calibration of light direction vector 58.JPG": "http://i3mainz.de/metadata/58.JPG_ld_calibration",
  "Calibration of light direction vector 59.JPG": "http://i3mainz.de/metadata/59.JPG_ld_calibration",
  "Calibration of light direction vector 6.JPG": "http://i3mainz.de/metadata/6.JPG_ld_calibration",
  "Calibration of light direction vector 60.JPG": "http://i3mainz.de/metadata/60.JPG_ld_calibration",
  "Calibration of light direction vector 7.JPG": "http://i3mainz.de/metadata/7.JPG_ld_calibration",
  "Calibration of light direction vector 8.JPG": "http://i3mainz.de/metadata/8.JPG_ld_calibration",
  "Calibration of light direction vector 9.JPG": "http://i3mainz.de/metadata/9.JPG_ld_calibration",
  "Dome Coordinate System X Axis": "http://i3mainz.de/metadata/DomeCoordinateSystem_axis1",
  "Dome Coordinate System Y Axis": "http://i3mainz.de/metadata/DomeCoordinateSystem_axis2",
  "Dome Coordinate System Z Axis": "http://i3mainz.de/metadata/DomeCoordinateSystem_axis3",
  "Image highlight point 0 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight0",
  "Image highlight point 0 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight0",
  "Image highlight point 0 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight0",
  "Image highlight point 0 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight0",
  "Image highlight point 1 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight1",
  "Image highlight point 1 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight1",
  "Image highlight point 1 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight1",
  "Image highlight point 1 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight1",
  "Image highlight point 10 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight10",
  "Image highlight point 10 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight10",
  "Image highlight point 10 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight10",
  "Image highlight point 10 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight10",
  "Image highlight point 11 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight11",
  "Image highlight point 11 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight11",
  "Image highlight point 11 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight11",
  "Image highlight point 11 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight11",
  "Image highlight point 12 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight12",
  "Image highlight point 12 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight12",
  "Image highlight point 12 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight12",
  "Image highlight point 12 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight12",
  "Image highlight point 13 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight13",
  "Image highlight point 13 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight13",
  "Image highlight point 13 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight13",
  "Image highlight point 13 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight13",
  "Image highlight point 14 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight14",
  "Image highlight point 14 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight14",
  "Image highlight point 14 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight14",
  "Image highlight point 14 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight14",
  "Image highlight point 15 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight15",
  "Image highlight point 15 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight15",
  "Image highlight point 15 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight15",
  "Image highlight point 15 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight15",
  "Image highlight point 16 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight16",
  "Image highlight point 16 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight16",
  "Image highlight point 16 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight16",
  "Image highlight point 16 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight16",
  "Image highlight point 17 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight17",
  "Image highlight point 17 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight17",
  "Image highlight point 17 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight17",
  "Image highlight point 17 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight17",
  "Image highlight point 18 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight18",
  "Image highlight point 18 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight18",
  "Image highlight point 18 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight18",
  "Image highlight point 18 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight18",
  "Image highlight point 19 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight19",
  "Image highlight point 19 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight19",
  "Image highlight point 19 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight19",
  "Image highlight point 19 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight19",
  "Image highlight point 2 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight2",
  "Image highlight point 2 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight2",
  "Image highlight point 2 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight2",
  "Image highlight point 2 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight2",
  "Image highlight point 20 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight20",
  "Image highlight point 20 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight20",
  "Image highlight point 20 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight20",
  "Image highlight point 20 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight20",
  "Image highlight point 21 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight21",
  "Image highlight point 21 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight21",
  "Image highlight point 21 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight21",
  "Image highlight point 21 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight21",
  "Image highlight point 22 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight22",
  "Image highlight point 22 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight22",
  "Image highlight point 22 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight22",
  "Image highlight point 22 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight22",
  "Image highlight point 23 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight23",
  "Image highlight point 23 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight23",
  "Image highlight point 23 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight23",
  "Image highlight point 23 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight23",
  "Image highlight point 24 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight24",
  "Image highlight point 24 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight24",
  "Image highlight point 24 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight24",
  "Image highlight point 24 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight24",
  "Image highlight point 25 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight25",
  "Image highlight point 25 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight25",
  "Image highlight point 25 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight25",
  "Image highlight point 25 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight25",
  "Image highlight point 26 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight26",
  "Image highlight point 26 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight26",
  "Image highlight point 26 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight26",
  "Image highlight point 26 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight26",
  "Image highlight point 27 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight27",
  "Image highlight point 27 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight27",
  "Image highlight point 27 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight27",
  "Image highlight point 27 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight27",
  "Image highlight point 28 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight28",
  "Image highlight point 28 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight28",
  "Image highlight point 28 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight28",
  "Image highlight point 28 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight28",
  "Image highlight point 29 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight29",
  "Image highlight point 29 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight29",
  "Image highlight point 29 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight29",
  "Image highlight point 29 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight29",
  "Image highlight point 3 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight3",
  "Image highlight point 3 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight3",
  "Image highlight point 3 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight3",
  "Image highlight point 3 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight3",
  "Image highlight point 30 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight30",
  "Image highlight point 30 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight30",
  "Image highlight point 30 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight30",
  "Image highlight point 30 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight30",
  "Image highlight point 31 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight31",
  "Image highlight point 31 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight31",
  "Image highlight point 31 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight31",
  "Image highlight point 31 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight31",
  "Image highlight point 32 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight32",
  "Image highlight point 32 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight32",
  "Image highlight point 32 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight32",
  "Image highlight point 32 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight32",
  "Image highlight point 33 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight33",
  "Image highlight point 33 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight33",
  "Image highlight point 33 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight33",
  "Image highlight point 33 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight33",
  "Image highlight point 34 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight34",
  "Image highlight point 34 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight34",
  "Image highlight point 34 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight34",
  "Image highlight point 34 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight34",
  "Image highlight point 35 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight35",
  "Image highlight point 35 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight35",
  "Image highlight point 35 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight35",
  "Image highlight point 35 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight35",
  "Image highlight point 36 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight36",
  "Image highlight point 36 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight36",
  "Image highlight point 36 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight36",
  "Image highlight point 36 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight36",
  "Image highlight point 37 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight37",
  "Image highlight point 37 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight37",
  "Image highlight point 37 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight37",
  "Image highlight point 37 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight37",
  "Image highlight point 38 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight38",
  "Image highlight point 38 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight38",
  "Image highlight point 38 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight38",
  "Image highlight point 38 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight38",
  "Image highlight point 39 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight39",
  "Image highlight point 39 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight39",
  "Image highlight point 39 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight39",
  "Image highlight point 39 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight39",
  "Image highlight point 4 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight4",
  "Image highlight point 4 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight4",
  "Image highlight point 4 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight4",
  "Image highlight point 4 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight4",
  "Image highlight point 40 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight40",
  "Image highlight point 40 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight40",
  "Image highlight point 40 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight40",
  "Image highlight point 40 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight40",
  "Image highlight point 41 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight41",
  "Image highlight point 41 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight41",
  "Image highlight point 41 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight41",
  "Image highlight point 41 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight41",
  "Image highlight point 42 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight42",
  "Image highlight point 42 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight42",
  "Image highlight point 42 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight42",
  "Image highlight point 42 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight42",
  "Image highlight point 43 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight43",
  "Image highlight point 43 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight43",
  "Image highlight point 43 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight43",
  "Image highlight point 43 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight43",
  "Image highlight point 44 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight44",
  "Image highlight point 44 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight44",
  "Image highlight point 44 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight44",
  "Image highlight point 44 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight44",
  "Image highlight point 45 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight45",
  "Image highlight point 45 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight45",
  "Image highlight point 45 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight45",
  "Image highlight point 45 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight45",
  "Image highlight point 46 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight46",
  "Image highlight point 46 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight46",
  "Image highlight point 46 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight46",
  "Image highlight point 46 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight46",
  "Image highlight point 47 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight47",
  "Image highlight point 47 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight47",
  "Image highlight point 47 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight47",
  "Image highlight point 47 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight47",
  "Image highlight point 48 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight48",
  "Image highlight point 48 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight48",
  "Image highlight point 48 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight48",
  "Image highlight point 48 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight48",
  "Image highlight point 49 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight49",
  "Image highlight point 49 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight49",
  "Image highlight point 49 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight49",
  "Image highlight point 49 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight49",
  "Image highlight point 5 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight5",
  "Image highlight point 5 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight5",
  "Image highlight point 5 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight5",
  "Image highlight point 5 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight5",
  "Image highlight point 50 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight50",
  "Image highlight point 50 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight50",
  "Image highlight point 50 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight50",
  "Image highlight point 50 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight50",
  "Image highlight point 51 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight51",
  "Image highlight point 51 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight51",
  "Image highlight point 51 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight51",
  "Image highlight point 51 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight51",
  "Image highlight point 52 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight52",
  "Image highlight point 52 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight52",
  "Image highlight point 52 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight52",
  "Image highlight point 52 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight52",
  "Image highlight point 53 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight53",
  "Image highlight point 53 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight53",
  "Image highlight point 53 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight53",
  "Image highlight point 53 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight53",
  "Image highlight point 54 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight54",
  "Image highlight point 54 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight54",
  "Image highlight point 54 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight54",
  "Image highlight point 54 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight54",
  "Image highlight point 55 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight55",
  "Image highlight point 55 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight55",
  "Image highlight point 55 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight55",
  "Image highlight point 55 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight55",
  "Image highlight point 56 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight56",
  "Image highlight point 56 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight56",
  "Image highlight point 56 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight56",
  "Image highlight point 56 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight56",
  "Image highlight point 57 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight57",
  "Image highlight point 57 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight57",
  "Image highlight point 57 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight57",
  "Image highlight point 57 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight57",
  "Image highlight point 58 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight58",
  "Image highlight point 58 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight58",
  "Image highlight point 58 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight58",
  "Image highlight point 58 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight58",
  "Image highlight point 59 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight59",
  "Image highlight point 59 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight59",
  "Image highlight point 59 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight59",
  "Image highlight point 59 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight59",
  "Image highlight point 6 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight6",
  "Image highlight point 6 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight6",
  "Image highlight point 6 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight6",
  "Image highlight point 6 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight6",
  "Image highlight point 7 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight7",
  "Image highlight point 7 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight7",
  "Image highlight point 7 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight7",
  "Image highlight point 7 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight7",
  "Image highlight point 8 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight8",
  "Image highlight point 8 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight8",
  "Image highlight point 8 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight8",
  "Image highlight point 8 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight8",
  "Image highlight point 9 using sphere 1": "http://i3mainz.de/metadata/project1_sphere1_highlight9",
  "Image highlight point 9 using sphere 2": "http://i3mainz.de/metadata/project1_sphere2_highlight9",
  "Image highlight point 9 using sphere 3": "http://i3mainz.de/metadata/project1_sphere3_highlight9",
  "Image highlight point 9 using sphere 4": "http://i3mainz.de/metadata/project1_sphere4_highlight9",
  "Light direction vector 0 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld0",
  "Light direction vector 0 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld0",
  "Light direction vector 0 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld0",
  "Light direction vector 0 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld0",
  "Light direction vector 1 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld1",
  "Light direction vector 1 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld1",
  "Light direction vector 1 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld1",
  "Light direction vector 1 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld1",
  "Light direction vector 1.JPG": "http://i3mainz.de/metadata/1.JPG_ld",
  "Light direction vector 10 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld10",
  "Light direction vector 10 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld10",
  "Light direction vector 10 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld10",
  "Light direction vector 10 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld10",
  "Light direction vector 10.JPG": "http://i3mainz.de/metadata/10.JPG_ld",
  "Light direction vector 11 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld11",
  "Light direction vector 11 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld11",
  "Light direction vector 11 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld11",
  "Light direction vector 11 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld11",
  "Light direction vector 11.JPG": "http://i3mainz.de/metadata/11.JPG_ld",
  "Light direction vector 12 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld12",
  "Light direction vector 12 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld12",
  "Light direction vector 12 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld12",
  "Light direction vector 12 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld12",
  "Light direction vector 12.JPG": "http://i3mainz.de/metadata/12.JPG_ld",
  "Light direction vector 13 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld13",
  "Light direction vector 13 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld13",
  "Light direction vector 13 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld13",
  "Light direction vector 13 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld13",
  "Light direction vector 13.JPG": "http://i3mainz.de/metadata/13.JPG_ld",
  "Light direction vector 14 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld14",
  "Light direction vector 14 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld14",
  "Light direction vector 14 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld14",
  "Light direction vector 14 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld14",
  "Light direction vector 14.JPG": "http://i3mainz.de/metadata/14.JPG_ld",
  "Light direction vector 15 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld15",
  "Light direction vector 15 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld15",
  "Light direction vector 15 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld15",
  "Light direction vector 15 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld15",
  "Light direction vector 15.JPG": "http://i3mainz.de/metadata/15.JPG_ld",
  "Light direction vector 16 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld16",
  "Light direction vector 16 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld16",
  "Light direction vector 16 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld16",
  "Light direction vector 16 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld16",
  "Light direction vector 16.JPG": "http://i3mainz.de/metadata/16.JPG_ld",
  "Light direction vector 17 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld17",
  "Light direction vector 17 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld17",
  "Light direction vector 17 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld17",
  "Light direction vector 17 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld17",
  "Light direction vector 17.JPG": "http://i3mainz.de/metadata/17.JPG_ld",
  "Light direction vector 18 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld18",
  "Light direction vector 18 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld18",
  "Light direction vector 18 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld18",
  "Light direction vector 18 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld18",
  "Light direction vector 18.JPG": "http://i3mainz.de/metadata/18.JPG_ld",
  "Light direction vector 19 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld19",
  "Light direction vector 19 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld19",
  "Light direction vector 19 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld19",
  "Light direction vector 19 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld19",
  "Light direction vector 19.JPG": "http://i3mainz.de/metadata/19.JPG_ld",
  "Light direction vector 2 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld2",
  "Light direction vector 2 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld2",
  "Light direction vector 2 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld2",
  "Light direction vector 2 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld2",
  "Light direction vector 2.JPG": "http://i3mainz.de/metadata/2.JPG_ld",
  "Light direction vector 20 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld20",
  "Light direction vector 20 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld20",
  "Light direction vector 20 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld20",
  "Light direction vector 20 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld20",
  "Light direction vector 20.JPG": "http://i3mainz.de/metadata/20.JPG_ld",
  "Light direction vector 21 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld21",
  "Light direction vector 21 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld21",
  "Light direction vector 21 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld21",
  "Light direction vector 21 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld21",
  "Light direction vector 21.JPG": "http://i3mainz.de/metadata/21.JPG_ld",
  "Light direction vector 22 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld22",
  "Light direction vector 22 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld22",
  "Light direction vector 22 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld22",
  "Light direction vector 22 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld22",
  "Light direction vector 22.JPG": "http://i3mainz.de/metadata/22.JPG_ld",
  "Light direction vector 23 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld23",
  "Light direction vector 23 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld23",
  "Light direction vector 23 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld23",
  "Light direction vector 23 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld23",
  "Light direction vector 23.JPG": "http://i3mainz.de/metadata/23.JPG_ld",
  "Light direction vector 24 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld24",
  "Light direction vector 24 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld24",
  "Light direction vector 24 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld24",
  "Light direction vector 24 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld24",
  "Light direction vector 24.JPG": "http://i3mainz.de/metadata/24.JPG_ld",
  "Light direction vector 25 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld25",
  "Light direction vector 25 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld25",
  "Light direction vector 25 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld25",
  "Light direction vector 25 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld25",
  "Light direction vector 25.JPG": "http://i3mainz.de/metadata/25.JPG_ld",
  "Light direction vector 26 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld26",
  "Light direction vector 26 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld26",
  "Light direction vector 26 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld26",
  "Light direction vector 26 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld26",
  "Light direction vector 26.JPG": "http://i3mainz.de/metadata/26.JPG_ld",
  "Light direction vector 27 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld27",
  "Light direction vector 27 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld27",
  "Light direction vector 27 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld27",
  "Light direction vector 27 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld27",
  "Light direction vector 27.JPG": "http://i3mainz.de/metadata/27.JPG_ld",
  "Light direction vector 28 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld28",
  "Light direction vector 28 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld28",
  "Light direction vector 28 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld28",
  "Light direction vector 28 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld28",
  "Light direction vector 28.JPG": "http://i3mainz.de/metadata/28.JPG_ld",
  "Light direction vector 29 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld29",
  "Light direction vector 29 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld29",
  "Light direction vector 29 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld29",
  "Light direction vector 29 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld29",
  "Light direction vector 29.JPG": "http://i3mainz.de/metadata/29.JPG_ld",
  "Light direction vector 3 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld3",
  "Light direction vector 3 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld3",
  "Light direction vector 3 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld3",
  "Light direction vector 3 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld3",
  "Light direction vector 3.JPG": "http://i3mainz.de/metadata/3.JPG_ld",
  "Light direction vector 30 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld30",
  "Light direction vector 30 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld30",
  "Light direction vector 30 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld30",
  "Light direction vector 30 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld30",
  "Light direction vector 30.JPG": "http://i3mainz.de/metadata/30.JPG_ld",
  "Light direction vector 31 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld31",
  "Light direction vector 31 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld31",
  "Light direction vector 31 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld31",
  "Light direction vector 31 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld31",
  "Light direction vector 31.JPG": "http://i3mainz.de/metadata/31.JPG_ld",
  "Light direction vector 32 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld32",
  "Light direction vector 32 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld32",
  "Light direction vector 32 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld32",
  "Light direction vector 32 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld32",
  "Light direction vector 32.JPG": "http://i3mainz.de/metadata/32.JPG_ld",
  "Light direction vector 33 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld33",
  "Light direction vector 33 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld33",
  "Light direction vector 33 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld33",
  "Light direction vector 33 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld33",
  "Light direction vector 33.JPG": "http://i3mainz.de/metadata/33.JPG_ld",
  "Light direction vector 34 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld34",
  "Light direction vector 34 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld34",
  "Light direction vector 34 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld34",
  "Light direction vector 34 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld34",
  "Light direction vector 34.JPG": "http://i3mainz.de/metadata/34.JPG_ld",
  "Light direction vector 35 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld35",
  "Light direction vector 35 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld35",
  "Light direction vector 35 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld35",
  "Light direction vector 35 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld35",
  "Light direction vector 35.JPG": "http://i3mainz.de/metadata/35.JPG_ld",
  "Light direction vector 36 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld36",
  "Light direction vector 36 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld36",
  "Light direction vector 36 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld36",
  "Light direction vector 36 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld36",
  "Light direction vector 36.JPG": "http://i3mainz.de/metadata/36.JPG_ld",
  "Light direction vector 37 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld37",
  "Light direction vector 37 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld37",
  "Light direction vector 37 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld37",
  "Light direction vector 37 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld37",
  "Light direction vector 37.JPG": "http://i3mainz.de/metadata/37.JPG_ld",
  "Light direction vector 38 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld38",
  "Light direction vector 38 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld38",
  "Light direction vector 38 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld38",
  "Light direction vector 38 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld38",
  "Light direction vector 38.JPG": "http://i3mainz.de/metadata/38.JPG_ld",
  "Light direction vector 39 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld39",
  "Light direction vector 39 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld39",
  "Light direction vector 39 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld39",
  "Light direction vector 39 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld39",
  "Light direction vector 39.JPG": "http://i3mainz.de/metadata/39.JPG_ld",
  "Light direction vector 4 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld4",
  "Light direction vector 4 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld4",
  "Light direction vector 4 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld4",
  "Light direction vector 4 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld4",
  "Light direction vector 4.JPG": "http://i3mainz.de/metadata/4.JPG_ld",
  "Light direction vector 40 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld40",
  "Light direction vector 40 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld40",
  "Light direction vector 40 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld40",
  "Light direction vector 40 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld40",
  "Light direction vector 40.JPG": "http://i3mainz.de/metadata/40.JPG_ld",
  "Light direction vector 41 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld41",
  "Light direction vector 41 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld41",
  "Light direction vector 41 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld41",
  "Light direction vector 41 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld41",
  "Light direction vector 41.JPG": "http://i3mainz.de/metadata/41.JPG_ld",
  "Light direction vector 42 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld42",
  "Light direction vector 42 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld42",
  "Light direction vector 42 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld42",
  "Light direction vector 42 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld42",
  "Light direction vector 42.JPG": "http://i3mainz.de/metadata/42.JPG_ld",
  "Light direction vector 43 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld43",
  "Light direction vector 43 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld43",
  "Light direction vector 43 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld43",
  "Light direction vector 43 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld43",
  "Light direction vector 43.JPG": "http://i3mainz.de/metadata/43.JPG_ld",
  "Light direction vector 44 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld44",
  "Light direction vector 44 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld44",
  "Light direction vector 44 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld44",
  "Light direction vector 44 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld44",
  "Light direction vector 44.JPG": "http://i3mainz.de/metadata/44.JPG_ld",
  "Light direction vector 45 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld45",
  "Light direction vector 45 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld45",
  "Light direction vector 45 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld45",
  "Light direction vector 45 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld45",
  "Light direction vector 45.JPG": "http://i3mainz.de/metadata/45.JPG_ld",
  "Light direction vector 46 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld46",
  "Light direction vector 46 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld46",
  "Light direction vector 46 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld46",
  "Light direction vector 46 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld46",
  "Light direction vector 46.JPG": "http://i3mainz.de/metadata/46.JPG_ld",
  "Light direction vector 47 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld47",
  "Light direction vector 47 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld47",
  "Light direction vector 47 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld47",
  "Light direction vector 47 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld47",
  "Light direction vector 47.JPG": "http://i3mainz.de/metadata/47.JPG_ld",
  "Light direction vector 48 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld48",
  "Light direction vector 48 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld48",
  "Light direction vector 48 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld48",
  "Light direction vector 48 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld48",
  "Light direction vector 48.JPG": "http://i3mainz.de/metadata/48.JPG_ld",
  "Light direction vector 49 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld49",
  "Light direction vector 49 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld49",
  "Light direction vector 49 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld49",
  "Light direction vector 49 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld49",
  "Light direction vector 49.JPG": "http://i3mainz.de/metadata/49.JPG_ld",
  "Light direction vector 5 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld5",
  "Light direction vector 5 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld5",
  "Light direction vector 5 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld5",
  "Light direction vector 5 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld5",
  "Light direction vector 5.JPG": "http://i3mainz.de/metadata/5.JPG_ld",
  "Light direction vector 50 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld50",
  "Light direction vector 50 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld50",
  "Light direction vector 50 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld50",
  "Light direction vector 50 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld50",
  "Light direction vector 50.JPG": "http://i3mainz.de/metadata/50.JPG_ld",
  "Light direction vector 51 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld51",
  "Light direction vector 51 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld51",
  "Light direction vector 51 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld51",
  "Light direction vector 51 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld51",
  "Light direction vector 51.JPG": "http://i3mainz.de/metadata/51.JPG_ld",
  "Light direction vector 52 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld52",
  "Light direction vector 52 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld52",
  "Light direction vector 52 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld52",
  "Light direction vector 52 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld52",
  "Light direction vector 52.JPG": "http://i3mainz.de/metadata/52.JPG_ld",
  "Light direction vector 53 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld53",
  "Light direction vector 53 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld53",
  "Light direction vector 53 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld53",
  "Light direction vector 53 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld53",
  "Light direction vector 53.JPG": "http://i3mainz.de/metadata/53.JPG_ld",
  "Light direction vector 54 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld54",
  "Light direction vector 54 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld54",
  "Light direction vector 54 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld54",
  "Light direction vector 54 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld54",
  "Light direction vector 54.JPG": "http://i3mainz.de/metadata/54.JPG_ld",
  "Light direction vector 55 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld55",
  "Light direction vector 55 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld55",
  "Light direction vector 55 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld55",
  "Light direction vector 55 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld55",
  "Light direction vector 55.JPG": "http://i3mainz.de/metadata/55.JPG_ld",
  "Light direction vector 56 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld56",
  "Light direction vector 56 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld56",
  "Light direction vector 56 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld56",
  "Light direction vector 56 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld56",
  "Light direction vector 56.JPG": "http://i3mainz.de/metadata/56.JPG_ld",
  "Light direction vector 57 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld57",
  "Light direction vector 57 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld57",
  "Light direction vector 57 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld57",
  "Light direction vector 57 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld57",
  "Light direction vector 57.JPG": "http://i3mainz.de/metadata/57.JPG_ld",
  "Light direction vector 58 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld58",
  "Light direction vector 58 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld58",
  "Light direction vector 58 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld58",
  "Light direction vector 58 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld58",
  "Light direction vector 58.JPG": "http://i3mainz.de/metadata/58.JPG_ld",
  "Light direction vector 59 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld59",
  "Light direction vector 59 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld59",
  "Light direction vector 59 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld59",
  "Light direction vector 59 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld59",
  "Light direction vector 59.JPG": "http://i3mainz.de/metadata/59.JPG_ld",
  "Light direction vector 6 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld6",
  "Light direction vector 6 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld6",
  "Light direction vector 6 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld6",
  "Light direction vector 6 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld6",
  "Light direction vector 6.JPG": "http://i3mainz.de/metadata/6.JPG_ld",
  "Light direction vector 60.JPG": "http://i3mainz.de/metadata/60.JPG_ld",
  "Light direction vector 7 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld7",
  "Light direction vector 7 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld7",
  "Light direction vector 7 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld7",
  "Light direction vector 7 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld7",
  "Light direction vector 7.JPG": "http://i3mainz.de/metadata/7.JPG_ld",
  "Light direction vector 8 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld8",
  "Light direction vector 8 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld8",
  "Light direction vector 8 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld8",
  "Light direction vector 8 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld8",
  "Light direction vector 8.JPG": "http://i3mainz.de/metadata/8.JPG_ld",
  "Light direction vector 9 for calbration object sphere 1": "http://i3mainz.de/metadata/project1_sphere1_ld9",
  "Light direction vector 9 for calbration object sphere 2": "http://i3mainz.de/metadata/project1_sphere2_ld9",
  "Light direction vector 9 for calbration object sphere 3": "http://i3mainz.de/metadata/project1_sphere3_ld9",
  "Light direction vector 9 for calbration object sphere 4": "http://i3mainz.de/metadata/project1_sphere4_ld9",
  "Light direction vector 9.JPG": "http://i3mainz.de/metadata/9.JPG_ld",
  "LightSource Group 0": "http://i3mainz.de/metadata/ledset_0",
  "LightSource Group 1": "http://i3mainz.de/metadata/ledset_1",
  "LightSource Group 10": "http://i3mainz.de/metadata/ledset_10",
  "LightSource Group 11": "http://i3mainz.de/metadata/ledset_11",
  "LightSource Group 12": "http://i3mainz.de/metadata/ledset_12",
  "LightSource Group 13": "http://i3mainz.de/metadata/ledset_13",
  "LightSource Group 14": "http://i3mainz.de/metadata/ledset_14",
  "LightSource Group 15": "http://i3mainz.de/metadata/ledset_15",
  "LightSource Group 16": "http://i3mainz.de/metadata/ledset_16",
  "LightSource Group 17": "http://i3mainz.de/metadata/ledset_17",
  "LightSource Group 18": "http://i3mainz.de/metadata/ledset_18",
  "LightSource Group 19": "http://i3mainz.de/metadata/ledset_19",
  "LightSource Group 2": "http://i3mainz.de/metadata/ledset_2",
  "LightSource Group 20": "http://i3mainz.de/metadata/ledset_20",
  "LightSource Group 21": "http://i3mainz.de/metadata/ledset_21",
  "LightSource Group 22": "http://i3mainz.de/metadata/ledset_22",
  "LightSource Group 23": "http://i3mainz.de/metadata/ledset_23",
  "LightSource Group 24": "http://i3mainz.de/metadata/ledset_24",
  "LightSource Group 25": "http://i3mainz.de/metadata/ledset_25",
  "LightSource Group 26": "http://i3mainz.de/metadata/ledset_26",
  "LightSource Group 27": "http://i3mainz.de/metadata/ledset_27",
  "LightSource Group 28": "http://i3mainz.de/metadata/ledset_28",
  "LightSource Group 29": "http://i3mainz.de/metadata/ledset_29",
  "LightSource Group 3": "http://i3mainz.de/metadata/ledset_3",
  "LightSource Group 30": "http://i3mainz.de/metadata/ledset_30",
  "LightSource Group 31": "http://i3mainz.de/metadata/ledset_31",
  "LightSource Group 32": "http://i3mainz.de/metadata/ledset_32",
  "LightSource Group 33": "http://i3mainz.de/metadata/ledset_33",
  "LightSource Group 34": "http://i3mainz.de/metadata/ledset_34",
  "LightSource Group 35": "http://i3mainz.de/metadata/ledset_35",
  "LightSource Group 36": "http://i3mainz.de/metadata/ledset_36",
  "LightSource Group 37": "http://i3mainz.de/metadata/ledset_37",
  "LightSource Group 38": "http://i3mainz.de/metadata/ledset_38",
  "LightSource Group 39": "http://i3mainz.de/metadata/ledset_39",
  "LightSource Group 4": "http://i3mainz.de/metadata/ledset_4",
  "LightSource Group 40": "http://i3mainz.de/metadata/ledset_40",
  "LightSource Group 41": "http://i3mainz.de/metadata/ledset_41",
  "LightSource Group 42": "http://i3mainz.de/metadata/ledset_42",
  "LightSource Group 43": "http://i3mainz.de/metadata/ledset_43",
  "LightSource Group 44": "http://i3mainz.de/metadata/ledset_44",
  "LightSource Group 45": "http://i3mainz.de/metadata/ledset_45",
  "LightSource Group 46": "http://i3mainz.de/metadata/ledset_46",
  "LightSource Group 47": "http://i3mainz.de/metadata/ledset_47",
  "LightSource Group 48": "http://i3mainz.de/metadata/ledset_48",
  "LightSource Group 49": "http://i3mainz.de/metadata/ledset_49",
  "LightSource Group 5": "http://i3mainz.de/metadata/ledset_5",
  "LightSource Group 50": "http://i3mainz.de/metadata/ledset_50",
  "LightSource Group 51": "http://i3mainz.de/metadata/ledset_51",
  "LightSource Group 52": "http://i3mainz.de/metadata/ledset_52",
  "LightSource Group 53": "http://i3mainz.de/metadata/ledset_53",
  "LightSource Group 54": "http://i3mainz.de/metadata/ledset_54",
  "LightSource Group 55": "http://i3mainz.de/metadata/ledset_55",
  "LightSource Group 56": "http://i3mainz.de/metadata/ledset_56",
  "LightSource Group 57": "http://i3mainz.de/metadata/ledset_57",
  "LightSource Group 58": "http://i3mainz.de/metadata/ledset_58",
  "LightSource Group 59": "http://i3mainz.de/metadata/ledset_59",
  "LightSource Group 6": "http://i3mainz.de/metadata/ledset_6",
  "LightSource Group 7": "http://i3mainz.de/metadata/ledset_7",
  "LightSource Group 8": "http://i3mainz.de/metadata/ledset_8",
  "LightSource Group 9": "http://i3mainz.de/metadata/ledset_9",
  "Measurement Project project1": "http://i3mainz.de/metadata/project1",
  "MeasurementSeries for Measurement Project project1": "http://i3mainz.de/metadata/project1_ms",
  "Pixel Coordinate System X Axis": "http://i3mainz.de/metadata/PixelCoordinateSystem_axis1",
  "Pixel Coordinate System Y Axis": "http://i3mainz.de/metadata/PixelCoordinateSystem_axis2",
  "project1 Calibration Sphere 1": "http://i3mainz.de/metadata/project1_sphere1",
  "project1 Calibration Sphere 1 Bounding Box": "http://i3mainz.de/metadata/project1_sphere1_bbox",
  "project1 Calibration Sphere 1 Centroid": "http://i3mainz.de/metadata/project1_sphere1_centroid",
  "project1 Calibration Sphere 2 Bounding Box": "http://i3mainz.de/metadata/project1_sphere2_bbox",
  "project1 Calibration Sphere 2 Centroid": "http://i3mainz.de/metadata/project1_sphere2_centroid",
  "project1 Calibration Sphere 3 Bounding Box": "http://i3mainz.de/metadata/project1_sphere3_bbox",
  "project1 Calibration Sphere 3 Centroid": "http://i3mainz.de/metadata/project1_sphere3_centroid",
  "project1 Calibration Sphere 4 Bounding Box": "http://i3mainz.de/metadata/project1_sphere4_bbox",
  "project1 Calibration Sphere 4 Centroid": "http://i3mainz.de/metadata/project1_sphere4_centroid"
}