var search={
  "Dome Coordinate System X Axis": "http://i3mainz.de/metadata/DomeCoordinateSystem_axis1",
  "Dome Coordinate System Y Axis": "http://i3mainz.de/metadata/DomeCoordinateSystem_axis2",
  "Dome Coordinate System Z Axis": "http://i3mainz.de/metadata/DomeCoordinateSystem_axis3",
  "Light direction vector 1.JPG": "http://i3mainz.de/metadata/1.JPG_ld",
  "Light direction vector 10.JPG": "http://i3mainz.de/metadata/10.JPG_ld",
  "Light direction vector 11.JPG": "http://i3mainz.de/metadata/11.JPG_ld",
  "Light direction vector 12.JPG": "http://i3mainz.de/metadata/12.JPG_ld",
  "Light direction vector 13.JPG": "http://i3mainz.de/metadata/13.JPG_ld",
  "Light direction vector 14.JPG": "http://i3mainz.de/metadata/14.JPG_ld",
  "Light direction vector 15.JPG": "http://i3mainz.de/metadata/15.JPG_ld",
  "Light direction vector 16.JPG": "http://i3mainz.de/metadata/16.JPG_ld",
  "Light direction vector 17.JPG": "http://i3mainz.de/metadata/17.JPG_ld",
  "Light direction vector 18.JPG": "http://i3mainz.de/metadata/18.JPG_ld",
  "Light direction vector 19.JPG": "http://i3mainz.de/metadata/19.JPG_ld",
  "Light direction vector 2.JPG": "http://i3mainz.de/metadata/2.JPG_ld",
  "Light direction vector 20.JPG": "http://i3mainz.de/metadata/20.JPG_ld",
  "Light direction vector 21.JPG": "http://i3mainz.de/metadata/21.JPG_ld",
  "Light direction vector 22.JPG": "http://i3mainz.de/metadata/22.JPG_ld",
  "Light direction vector 23.JPG": "http://i3mainz.de/metadata/23.JPG_ld",
  "Light direction vector 24.JPG": "http://i3mainz.de/metadata/24.JPG_ld",
  "Light direction vector 25.JPG": "http://i3mainz.de/metadata/25.JPG_ld",
  "Light direction vector 26.JPG": "http://i3mainz.de/metadata/26.JPG_ld",
  "Light direction vector 27.JPG": "http://i3mainz.de/metadata/27.JPG_ld",
  "Light direction vector 28.JPG": "http://i3mainz.de/metadata/28.JPG_ld",
  "Light direction vector 29.JPG": "http://i3mainz.de/metadata/29.JPG_ld",
  "Light direction vector 3.JPG": "http://i3mainz.de/metadata/3.JPG_ld",
  "Light direction vector 30.JPG": "http://i3mainz.de/metadata/30.JPG_ld",
  "Light direction vector 31.JPG": "http://i3mainz.de/metadata/31.JPG_ld",
  "Light direction vector 32.JPG": "http://i3mainz.de/metadata/32.JPG_ld",
  "Light direction vector 33.JPG": "http://i3mainz.de/metadata/33.JPG_ld",
  "Light direction vector 34.JPG": "http://i3mainz.de/metadata/34.JPG_ld",
  "Light direction vector 35.JPG": "http://i3mainz.de/metadata/35.JPG_ld",
  "Light direction vector 36.JPG": "http://i3mainz.de/metadata/36.JPG_ld",
  "Light direction vector 37.JPG": "http://i3mainz.de/metadata/37.JPG_ld",
  "Light direction vector 38.JPG": "http://i3mainz.de/metadata/38.JPG_ld",
  "Light direction vector 39.JPG": "http://i3mainz.de/metadata/39.JPG_ld",
  "Light direction vector 4.JPG": "http://i3mainz.de/metadata/4.JPG_ld",
  "Light direction vector 40.JPG": "http://i3mainz.de/metadata/40.JPG_ld",
  "Light direction vector 41.JPG": "http://i3mainz.de/metadata/41.JPG_ld",
  "Light direction vector 42.JPG": "http://i3mainz.de/metadata/42.JPG_ld",
  "Light direction vector 43.JPG": "http://i3mainz.de/metadata/43.JPG_ld",
  "Light direction vector 44.JPG": "http://i3mainz.de/metadata/44.JPG_ld",
  "Light direction vector 45.JPG": "http://i3mainz.de/metadata/45.JPG_ld",
  "Light direction vector 46.JPG": "http://i3mainz.de/metadata/46.JPG_ld",
  "Light direction vector 47.JPG": "http://i3mainz.de/metadata/47.JPG_ld",
  "Light direction vector 48.JPG": "http://i3mainz.de/metadata/48.JPG_ld",
  "Light direction vector 49.JPG": "http://i3mainz.de/metadata/49.JPG_ld",
  "Light direction vector 5.JPG": "http://i3mainz.de/metadata/5.JPG_ld",
  "Light direction vector 50.JPG": "http://i3mainz.de/metadata/50.JPG_ld",
  "Light direction vector 51.JPG": "http://i3mainz.de/metadata/51.JPG_ld",
  "Light direction vector 52.JPG": "http://i3mainz.de/metadata/52.JPG_ld",
  "Light direction vector 53.JPG": "http://i3mainz.de/metadata/53.JPG_ld",
  "Light direction vector 54.JPG": "http://i3mainz.de/metadata/54.JPG_ld",
  "Light direction vector 55.JPG": "http://i3mainz.de/metadata/55.JPG_ld",
  "Light direction vector 56.JPG": "http://i3mainz.de/metadata/56.JPG_ld",
  "Light direction vector 57.JPG": "http://i3mainz.de/metadata/57.JPG_ld",
  "Light direction vector 58.JPG": "http://i3mainz.de/metadata/58.JPG_ld",
  "Light direction vector 59.JPG": "http://i3mainz.de/metadata/59.JPG_ld",
  "Light direction vector 6.JPG": "http://i3mainz.de/metadata/6.JPG_ld",
  "Light direction vector 60.JPG": "http://i3mainz.de/metadata/60.JPG_ld",
  "Light direction vector 7.JPG": "http://i3mainz.de/metadata/7.JPG_ld",
  "Light direction vector 8.JPG": "http://i3mainz.de/metadata/8.JPG_ld",
  "Light direction vector 9.JPG": "http://i3mainz.de/metadata/9.JPG_ld",
  "Measurement Project project1": "http://i3mainz.de/metadata/project1",
  "MeasurementSeries for Measurement Project project1": "http://i3mainz.de/metadata/project1_ms",
  "Pixel Coordinate System X Axis": "http://i3mainz.de/metadata/PixelCoordinateSystem_axis1",
  "Pixel Coordinate System Y Axis": "http://i3mainz.de/metadata/PixelCoordinateSystem_axis2",
  "project1 Calibration Sphere 1": "http://i3mainz.de/metadata/project1_sphere1"
}