name: Java CI

on: [push]

jobs:
    
  ontdocI:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc I      
    with: 
          rdffilepath: sampleRTI.ttl
          docpath: docs/sampleRTI/
          prefixns: https://situx.github.io/sampleRTImetadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: sampleRTI/

  ontdocII:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc II      
    with: 
          rdffilepath: resgraph_oscar.ttl
          docpath: docs/oscar/
          prefixns: http://i3mainz.de/metadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: oscar/
  
  ontdocIII:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc III      
    with: 
          rdffilepath: resgraph_rtibuilder.ttl
          docpath: docs/rtibuilder/
          prefixns: http://i3mainz.de/metadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: rtibuilder/

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Initial checkout
      uses: actions/checkout@v1
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
