name: Java CI

on: [push]

jobs:
    
  ontdocI:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc I      
    with: 
          version: v017dev
          rdffilepath: sampleRTI.ttl
          docpath: docs/sampleRTI/
          prefixns: https://situx.github.io/sampleRTImetadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: sampleRTI/

  ontdocII:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc II      
    with: 
          version: v017dev
          rdffilepath: resgraph_oscar.ttl
          docpath: docs/oscar/
          prefixns: http://i3mainz.de/metadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: oscar/
  
  ontdocIII:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc III      
    with: 
          version: v017dev
          rdffilepath: resgraph_rtibuilder.ttl
          docpath: docs/rtibuilder/
          prefixns: http://i3mainz.de/metadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: rtibuilder/

  ontdocIV:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc IV      
    with: 
          version: v017dev
          rdffilepath: resgraph_relight.ttl
          docpath: docs/relight/
          prefixns: http://i3mainz.de/metadata/
          prefixnsshort: ex
          indexpages: true
          metadatatable: true
          createcollections: false
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: relight/
